name: C/C++ CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: linux

    steps:
    - uses: actions/checkout@v2
    - name: configure
      run: ./configure-cmake
    - name: make
      run: make
    - name: make test
      run: make test
    - name: make install
      run: make install
